In [1]:
import numpy as np


In [10]:
x = np.arange(1,25).reshape(2, 4, 3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [12]:
x.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
y = x.reshape(4,6)
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [22]:
np.sum(y, axis=1)

array([ 21,  57,  93, 129])

In [32]:
a = np.arange(1,13).reshape(2,2,3)
b = np.arange(13,25).reshape(2,2,3)
print(a)
print('-'*20)
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
--------------------
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


In [41]:
np.sum(a, axis=2)

array([[ 6, 15],
       [24, 33]])

In [44]:
a[:, 1, 1:]

array([[ 5,  6],
       [11, 12]])

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)
print(torch.cuda.is_available())

2.9.1+cpu
False
